### ISSUE TITLE
I want my search preferences hardcoded 

### ISSUE THREAD

**Issue by sh3ll4rpw** [omkarcloud/google-maps-scraper#10]
In my opinion a scraper is for bulk. Not for single searches with each different search preferences. I don't think it's practical to add search preferences for EACH search query in config.py. No serious user is doing that? And it's also a lot of extra work for people that are not familiar with text-processesing to add this for every query. It's better to have it hardcoded like in V1.

I use code that import my queries from excel and I use`queries = varlist` without `"max_results" : 5,`. So now I can't set my own search preferences anymore. So I need it hardcoded again.

 What code do I need to scrape_google_maps_places_task.py to make the search preferences hardcoded again like in V1?

I only want to fetch links with a website

**Comment by sh3ll4rpw** [comment]
filter_data = { } option in V1 was perfect. I really don't like the new approach. It's ok to add filter_data = { } to config.py. But please let me set the filter_data for all queries and not for a single query. 

And what happened with the filter_data option for fetching links? The code below in V1 was not working for me. I did still get data WITHOUT website.
```
    filter_data = {
            #  "min_rating" : 3, 
            #  "min_reviews" : 5, 
            #  "max_reviews" : 100, 
            #  "has_phone" : True, 
              "has_website" : True, 
        }
```

But the this one was doing its job
                print(f'Fetched {len(links)} links.')

                # filter_data = {
                #     "min_reviews": 5,
                     "has_website": True,
                # }
```

I don't want to fetch searches without webite at all. Its cleaner like that. How do I add the fetch filter_data option back?

**Comment by Chetan11-dev** [comment]
I don't know what to do. Let's see what the community says.
