### ISSUE TITLE
Can't find the option to fetch resturant menus using this API

### ISSUE THREAD

**Issue by Prottoy2938** [omkarcloud/google-maps-scraper#106]
Trying to fetch restaurant menus (using their placeID) , but don't seem to see any options/variables to fetch menus.

Does this libary supports resturants menu fetching?

If not, what can I do? Looked into all other libraries, but this one seemed most promising.

**Comment by Chetan11-dev** [comment]
Thank you, @Prottoy2938, for opening the issue and using our Google Maps Scraper Tool.
Also, I am attached sample of restaurants in New York, so you may see what is scraped:
[restraunts-in-new-york.zip](https://github.com/omkarcloud/google-maps-scraper/files/14025236/restraunts-in-new-york.zip)

**Comment by Prottoy2938** [comment]
I see.

Is it possible to fetch data based on google maps `placeID`?
