### ISSUE TITLE
On the PRO 

### ISSUE THREAD

**Issue by Iamtheoldman** [omkarcloud/google-maps-scraper#108]
How do we scrape based on company category?

**Comment by Chetan11-dev** [comment]
Thank you, @USERNAME, for opening the issue and using our Google Maps Scraper Tool. Also, you may use the following code to get categories
```
Gmaps.places(queries, category_in=[Gmaps.Category.DentalClinic, Gmaps.Category.DentalLaboratory])
```

**Comment by Iamtheoldman** [comment]
Pro version is not working

**Comment by Chetan11-dev** [comment]
- Kindly send email to chetan@omkar.cloud so I can the last python node version dated 4th October
- If all you want is to run in Server, I recommend running in Google Cloud by following https://github.com/omkarcloud/botasaurus?tab=readme-ov-file#how-to-run-scraper-in-virtual-machine, you won't face any issues. 
- Docker has been unreliable to run.
