### ISSUE TITLE
GET FIRSTPAGE TRUE

### ISSUE THREAD

**Issue by sh3ll4rpw** [omkarcloud/google-maps-scraper#11]
What happened with the FIRSTPAGE option? For me it was the most important option V1 had. How to add it back?

**Comment by Chetan11-dev** [comment]
I don't know what to do. Let's see what the community says.

**Comment by sh3ll4rpw** [comment]
That is very sad. Can't I select a maximum amount of links I want to scrape each search query? For example max 10 results for each for query. I don't want to scrape 30 pages when I only need even less than the first page. It will burn IPs, cost more time to scrape and force me to check the results and manually delete more than 80%

**Comment by Chetan11-dev** [comment]
You can use max_results param.
