### ISSUE TITLE
Botasaurus install

### ISSUE THREAD

**Issue by jontje12** [omkarcloud/google-maps-scraper#115]
### Description
When running python -m pip install -r requirements.txt I get the following error: note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

Because of this, Botasaurus can't install and the program can't run
[Description of the issue]

### Code to Reproduce (Paste `main.py`)

```python
```

### Zip and Upload the `error_log/` Folder (Optional, if there are errors)

**Comment by Chetan11-dev** [comment]
Kindly run 
python -m pip install botasaurus --upgrade
If it occurs again, run please attach screenshot.

**Comment by jontje12** [comment]
Didn't work unfortunately..
![Maps Scraper Prob](https://github.com/omkarcloud/google-maps-scraper/assets/157704572/ce847f83-f11f-4439-87fb-6380ab6ebcd4)

**Comment by Chetan11-dev** [comment]
Kindly run it again

**Comment by jontje12** [comment]
Still doesn't work, does get further than the first time though
![Maps Scraper Prob 2](https://github.com/omkarcloud/google-maps-scraper/assets/157704572/9539e3c4-f8f4-4a38-9fe1-b4131e1644ee)

**Comment by Chetan11-dev** [comment]
I have released a fix. Please run, it again.

```
python -m pip install botasaurus --upgrade
```
