### ISSUE TITLE
PRO emails

### ISSUE THREAD

**Issue by jontje12** [omkarcloud/google-maps-scraper#116]
### Description

Hi! I bought the PRO version as I thought this is a great script to run to get emails from companies on Google Maps really quick.
It says emails are supported but when running the program, no emails show up only the websites and name.
How do I get the emails from the scanned sites and is it possible to have them all in a separate column in the Excel output? 
Otherwise the PRO version would not be useful to me.

### Code to Reproduce (Paste `main.py`)

```
queries = [
   "web developers in bangalore"
]

fields = [
   Gmaps.Fields.NAME, 
   Gmaps.Fields.EMAILS, 
   Gmaps.Fields.LINK, 
]

Gmaps.places(queries, fields=fields)
```
Like in this file. Is this possible with this scraper?
[bedrijveninfo+email.xlsx](https://github.com/omkarcloud/google-maps-scraper/files/14095896/bedrijveninfo%2Bemail.xlsx)

### Zip and Upload the `error_log/` Folder (Optional, if there are errors)

**Comment by Chetan11-dev** [comment]
You need to use the [api](https://github.com/omkarcloud/google-maps-scraper#-how-do-i-scrape-social-details-of-profiles-like-email-facebook-twitter-etc) integration.

**Comment by jontje12** [comment]
I use the following code:
queries = [
   "aannemer in Delft"
]

fields = [
   Gmaps.Fields.NAME, 
   Gmaps.Fields.EMAILS, 
   Gmaps.Fields.LINK, 
]

Gmaps.places(queries, max=5, key=f77a761946msh982e12753dabe1dp100d13jsn63b54b1f308f)

With f77a761946msh982e12753dabe1dp100d13jsn63b54b1f308f being my API key but it still doesn't work

**Comment by Chetan11-dev** [comment]
I deleted your comment because you should not leak the API keys. Also, please change the keys by going to https://rapidapi.com/developer/apps > Authorization. Regarding your question, you need to enclose the key in brackets. For example:

```python
queries = [
    "aannemer in Delft"
]

fields = [
    Gmaps.Fields.NAME,
    Gmaps.Fields.EMAILS,
    Gmaps.Fields.LINK,
]

Gmaps.places(queries, max=5, key="f77a761946msh982e12753dabe1dp100d13jsn63b54b1f308f")
```

**Comment by jontje12** [comment]
It works now, but the emails it gets are in one big line which means they are not easily exportable. Can I get just the emails in one column?

**Comment by Chetan11-dev** [comment]
Unfortunately, It is not supported as of now.
