### ISSUE TITLE
javascript fixed related with botsaurus

### ISSUE THREAD

**Issue by jdevsan** [omkarcloud/google-maps-scraper#120]
### Description
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: botasaurus, botasaurus-proxy-authentication, capsolver_extension_python, javascript_fixes, chrome_extension_python
  Building wheel for botasaurus (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [152 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\botasaurus
      copying botasaurus\accept_google_cookies.py -> build\lib\botasaurus
      copying botasaurus\anti_detect_driver.py -> build\lib\botasaurus
      copying botasaurus\anti_detect_requests.py -> build\lib\botasaurus
      copying botasaurus\base_data.py -> build\lib\botasaurus
      copying botasaurus\beep_utils.py -> build\lib\botasaurus
      copying botasaurus\botasaurus_storage.py -> build\lib\botasaurus
      copying botasaurus\bt.py -> build\lib\botasaurus
      copying botasaurus\cache.py -> build\lib\botasaurus
      copying botasaurus\calc_max_parallel_browsers.py -> build\lib\botasaurus
      copying botasaurus\check_and_download_driver.py -> build\lib\botasaurus
      copying botasaurus\chrome_launcher_adapter.py -> build\lib\botasaurus
      copying botasaurus\cl.py -> build\lib\botasaurus
      copying botasaurus\close.py -> build\lib\botasaurus
      copying botasaurus\create_driver_utils.py -> build\lib\botasaurus
      copying botasaurus\create_stealth_driver.py -> build\lib\botasaurus
      copying botasaurus\creators.py -> build\lib\botasaurus
      copying botasaurus\decorators.py -> build\lib\botasaurus
      copying botasaurus\decorators_utils.py -> build\lib\botasaurus
      copying botasaurus\decorator_helpers.py -> build\lib\botasaurus
      copying botasaurus\download_driver.py -> build\lib\botasaurus
      copying botasaurus\driver_about.py -> build\lib\botasaurus
      copying botasaurus\exceptions.py -> build\lib\botasaurus
      copying botasaurus\formats.py -> build\lib\botasaurus
      copying botasaurus\get_chrome_version.py -> build\lib\botasaurus
      copying botasaurus\got_adapter.py -> build\lib\botasaurus
      copying botasaurus\ip_utils.py -> build\lib\botasaurus
      copying botasaurus\list_utils.py -> build\lib\botasaurus
      copying botasaurus\local_storage.py -> build\lib\botasaurus
      copying botasaurus\local_storage_driver.py -> build\lib\botasaurus
      copying botasaurus\opponent.py -> build\lib\botasaurus
      copying botasaurus\output.py -> build\lib\botasaurus
      copying botasaurus\profile.py -> build\lib\botasaurus
      copying botasaurus\temp_mail.py -> build\lib\botasaurus
      copying botasaurus\usage.py -> build\lib\botasaurus
      copying botasaurus\user_agent.py -> build\lib\botasaurus
      copying botasaurus\user_generator.py -> build\lib\botasaurus
      copying botasaurus\utils.py -> build\lib\botasaurus
      copying botasaurus\wait.py -> build\lib\botasaurus
      copying botasaurus\window_size.py -> build\lib\botasaurus
      copying botasaurus\_id.py -> build\lib\botasaurus
      copying botasaurus\__init__.py -> build\lib\botasaurus
      C:\Users\lehso\miniconda3\envs\mapscrapper\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build\bdist.win-amd64\wheel
      running install
      running install_lib
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      creating build\bdist.win-amd64\wheel\botasaurus
      copying build\lib\botasaurus\accept_google_cookies.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\anti_detect_driver.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\anti_detect_requests.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\base_data.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\beep_utils.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\botasaurus_storage.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\bt.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\cache.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\calc_max_parallel_browsers.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\check_and_download_driver.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\chrome_launcher_adapter.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\cl.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\close.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\create_driver_utils.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\create_stealth_driver.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\creators.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\decorators.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\decorators_utils.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\decorator_helpers.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\download_driver.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\driver_about.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\exceptions.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\formats.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\get_chrome_version.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\got_adapter.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\ip_utils.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\list_utils.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\local_storage.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\local_storage_driver.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\opponent.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\output.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\profile.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\temp_mail.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\usage.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\user_agent.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\user_generator.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\utils.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\wait.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\window_size.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\_id.py -> build\bdist.win-amd64\wheel\.\botasaurus
      copying build\lib\botasaurus\__init__.py -> build\bdist.win-amd64\wheel\.\botasaurus
      running install_egg_info
      running egg_info
      writing botasaurus.egg-info\PKG-INFO
      writing dependency_links to botasaurus.egg-info\dependency_links.txt
      writing requirements to botasaurus.egg-info\requires.txt
      writing top-level names to botasaurus.egg-info\top_level.txt
      reading manifest file 'botasaurus.egg-info\SOURCES.txt'
      adding license file 'LICENSE'
      adding license file 'AUTHORS'
      writing manifest file 'botasaurus.egg-info\SOURCES.txt'
      Copying botasaurus.egg-info to build\bdist.win-amd64\wheel\.\botasaurus-3.2.17-py3.10.egg-info
      running install_scripts
      Installing needed npm packages
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lehso\AppData\Local\Temp\pip-install-ar0cvmgc\botasaurus_b43c2e2d6899458d9ea9d8a4386038ca\setup.py", line 111, in <module>
          setup(
        File "C:\Users\lehso\miniconda3\envs\mapscrapper\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\lehso\miniconda3\envs\mapscrapper\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\lehso\miniconda3\envs\mapscrapper\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\lehso\miniconda3\envs\mapscrapper\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\lehso\miniconda3\envs\mapscrapper\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\lehso\miniconda3\envs\mapscrapper\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\lehso\miniconda3\envs\mapscrapper\lib\site-packages\wheel\bdist_wheel.py", line 399, in run
          self.run_command("install")
        File "C:\Users\lehso\miniconda3\envs\mapscrapper\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\lehso\miniconda3\envs\mapscrapper\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\lehso\miniconda3\envs\mapscrapper\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\lehso\AppData\Local\Temp\pip-install-ar0cvmgc\botasaurus_b43c2e2d6899458d9ea9d8a4386038ca\setup.py", line 106, in run
          post_install()
        File "C:\Users\lehso\AppData\Local\Temp\pip-install-ar0cvmgc\botasaurus_b43c2e2d6899458d9ea9d8a4386038ca\setup.py", line 94, in post_install
          install_npm_package("chrome-launcher")
        File "C:\Users\lehso\AppData\Local\Temp\pip-install-ar0cvmgc\botasaurus_b43c2e2d6899458d9ea9d8a4386038ca\setup.py", line 38, in install_npm_package
          from javascript_fixes.packageinstall import packageinstall
      ModuleNotFoundError: No module named 'javascript_fixes'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for botasaurus
  Running setup.py clean for botasaurus
  Building wheel for botasaurus-proxy-authentication (setup.py) ... done
  Created wheel for botasaurus-proxy-authentication: filename=botasaurus_proxy_authentication-1.0.9-py3-none-any.whl size=4337 sha256=7b7457ecb0e482515c7bdc2105cd8ac1d760d59c4cdfb0af5d0ac02134f7af06
  Stored in directory: c:\users\lehso\appdata\local\pip\cache\wheels\09\9a\0e\c292d323f75174df64c69781ba9ef498cf37d69b8ffc2b6f31
  Building wheel for capsolver_extension_python (setup.py) ... done
  Created wheel for capsolver_extension_python: filename=capsolver_extension_python-1.0.1-py3-none-any.whl size=4009 sha256=b02444e338010d448eac38f9b653172afff0831f8aeb3185e7db2807f459842a
  Stored in directory: c:\users\lehso\appdata\local\pip\cache\wheels\aa\4c\cc\ab46177d5e7c1ce99c9505ac63a673a68295897413420ffe82
  Building wheel for javascript_fixes (setup.py) ... done
  Created wheel for javascript_fixes: filename=javascript_fixes-1.1.4-py3-none-any.whl size=24950 sha256=ff31222be162b2d28e12fe89163fe8edfe22993918c052eb1542cf8ba55bd7a7
  Stored in directory: c:\users\lehso\appdata\local\pip\cache\wheels\e2\bf\e4\9f7b7104e3b615c699efdc33ab2cc9bf5da3fc9f98e8a1e07f
  Building wheel for chrome_extension_python (setup.py) ... done
  Created wheel for chrome_extension_python: filename=chrome_extension_python-1.0.1-py3-none-any.whl size=7808 sha256=a11180f483c510a5c25a02f3f115afa56a43ede0a8660e81ac5d7576a6d07431
  Stored in directory: c:\users\lehso\appdata\local\pip\cache\wheels\31\ee\0a\185db5dc334b05613ca20eab0ea7e1f068f9911112d1cb5458
Successfully built botasaurus-proxy-authentication capsolver_extension_python javascript_fixes chrome_extension_python
Failed to build botasaurus
ERROR: Could not build wheels for botasaurus, which is required to install pyproject.toml-based projects

[Description of the issue]

### Code to Reproduce (Paste `main.py`)

```python
```

### Zip and Upload the `error_log/` Folder (Optional, if there are errors)

**Comment by Chetan11-dev** [comment]
Kindly Run
python -m pip install botasaurus --upgrade
