### ISSUE TITLE
Google maps was stuck on scrolling

### ISSUE THREAD

**Issue by websines** [omkarcloud/google-maps-scraper#121]
```queries = Gmaps.Cities.UnitedStates("restaurants in ")[1:100]```
```Gmaps.places(queries, has_website=False, has_phone=True, max_reviews=100)```

#Output:
```DevTools listening on ws://127.0.0.1:51504/devtools/browser/f86a7b1d-b0ba-4cb2-b7d8-46716a3d41fb```

```Google Maps was stuck in scrolling. Retrying.```

**Comment by nbapera** [comment]
Have you fixed this yet?
