### ISSUE TITLE
FED-UP WANT MY $100 contributions back now :( 

### ISSUE THREAD

**Issue by 007-JB** [omkarcloud/google-maps-scraper#126]
### Description

[Description of the issue]

### Code to Reproduce (Paste `main.py`)

```python
```

### Zip and Upload the `error_log/` Folder (Optional, if there are errors)

**Comment by 007-JB** [comment]
I'm honestly fed up by now... I paid so much - each time it fails to work a quick fix is put in place (hooray) - only to me disappointment its not working the next time I run it without having changed a thing.

I've flagged this before but no resolve- so seeking to take  action for what appeared like a great product, seemed worth upgrading to the pro version - at a cost of something like $30  a pop - 

C:\Users\jbard\google-maps-scraper-pro-master>python main.py
Task Started
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664 Safari/537.36

DevTools listening on ws://127.0.0.1:63692/devtools/browser/82abc241-6688-4156-a597-9a5257305fe8
Launched Browser
[25816:27620:0217/144356.818:ERROR:usb_descriptors.cc(141)] Failed to read length for configuration 1.
[25816:27620:0217/144356.818:ERROR:usb_descriptors.cc(100)] Failed to read all configuration descriptors. Expected 2, got 1.
[25816:27620:0217/144356.819:ERROR:device_event_log_impl.cc(192)] [14:43:56.819] USB: usb_device_win.cc:95 Failed to read descriptors from \\?\usb#vid_0bda&pid_8152#207bd52a264a#{a5dcbf10-6530-11d2-901f-00c04fb951ed}.
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Fetched 111 links.
0 https://www.google.com/maps/place/Zahrat+Al+Rawdah+Pharmacy+320+%D8%B5%D9%8A%D8%AF%D9%84%D9%8A%D8%A9+%D8%B2%D9%87%D8%B1%D8%A9+%D8%A7%D9%84%D8%B1%D9%88%D8%B6%D8%A9%E2%80%AD/data=!4m7!3m6!1s0x3e2f1d3e89f92ed1:0xce261705c673a1fe!8m2!3d24.6883073!4d46.6463607!16s%2Fg%2F11tf2tr1qy!19sChIJ0S75iT4dLz4R_qFzxgUXJs4?authuser=0&hl=en&rclk=1
1 https://www.google.com/maps/place/PLUS+ONE+PHARMACY+6/data=!4m7!3m6!1s0x3e2f056b5f1e5f81:0x7421df8dc2125af2!8m2!3d24.6672184!4d46.7131314!16s%2Fg%2F11lh_wnz26!19sChIJgV8eX2sFLz4R8loSwo3fIXQ?authuser=0&hl=en&rclk=1
2 https://www.google.com/maps/place/Family+Basket+pharmacy+%D8%B5%D9%8A%D8%AF%D9%84%D9%8A%D8%A9+%D8%B3%D9%84%D8%A9+%D8%A7%D9%84%D8%B9%D8%A7%D8%A6%D9%84%D8%A9%E2%80%AD/data=!4m7!3m6!1s0x3e2f03733b75e7ad:0xa22c55de7ebccd22!8m2!3d24.6962287!4d46.7025945!16s%2Fg%2F12hxp3qb6!19sChIJred1O3MDLz4RIs28ft5VLKI?authuser=0&hl=en&rclk=1
3 https://www.google.com/maps/place/Alhabib+Pharmacy/data=!4m7!3m6!1s0x3e2f1d6515ae52d9:0x7aeb6fedea40b6f!8m2!3d24.7201944!4d46.6569641!16s%2Fg%2F11gmb64vgp!19sChIJ2VKuFWUdLz4Rbwuk3v62rgc?authuser=0&hl=en&rclk=1
4 https://www.google.com/maps/place/Al+Badri+Pharmacy/data=!4m7!3m6!1s0x3e2efddadc25c7cb:0xf8a8abe460ac01bd!8m2!3d24.757619!4d46.6855474!16s%2Fg%2F11g0tq9l7m!19sChIJy8cl3Nr9Lj4RvQGsYOSrqPg?authuser=0&hl=en&rclk=1
5 https://www.google.com/maps/place/Al+Khalifah+Pharmacy/data=!4m7!3m6!1s0x3e2f047823ea2edf:0xd786cc9525cdd7de!8m2!3d24.682243!4d46.7185017!16s%2Fg%2F11_tgyjn2!19sChIJ3y7qI3gELz4R3tfNJZXMhtc?authuser=0&hl=en&rclk=1
6 https://www.google.com/maps/place/Nahdi+Pharmacy/data=!4m7!3m6!1s0x3e2f1d1800606989:0x75ece2a2dd0530d1!8m2!3d24.6994!4d46.6432!16s%2Fg%2F11fs1xhpqc!19sChIJiWlgABgdLz4R0TAF3aLi7HU?authuser=0&hl=en&rclk=1
7 https://www.google.com/maps/place/Nahdi+pharmacy/data=!4m7!3m6!1s0x3e2ee3b549bf8b53:0x8a16cbda1c92c55c!8m2!3d24.7380993!4d46.6071023!16s%2Fg%2F11c55tr7fp!19sChIJU4u_SbXjLj4RXMWSHNrLFoo?authuser=0&hl=en&rclk=1
8 https://www.google.com/maps/place/%D9%86%D8%A8%D8%BA%D8%A7%D9%83+%D8%B7%D9%8A%D8%A8+To+Be+Well%E2%80%AD/data=!4m7!3m6!1s0x3e2ee33abb40e219:0x739c09d8ff671a83!8m2!3d24.8012772!4d46.6473808!16s%2Fg%2F11rckz68fr!19sChIJGeJAuzrjLj4Rgxpn_9gJnHM?authuser=0&hl=en&rclk=1
9 https://www.google.com/maps/place/Boots+pharmacy/data=!4m7!3m6!1s0x3e2f03393213b50b:0xd8db8f0fbe1a256!8m2!3d24.689533!4d46.6856!16s%2Fg%2F11bwprt8j5!19sChIJC7UTMjkDLz4RVqLh-_C4jQ0?authuser=0&hl=en&rclk=1
10 https://www.google.com/maps/place/Ghodaf+Pharmacy/data=!4m7!3m6!1s0x3e2f028040a3c447:0xe268e427c9b54d4a!8m2!3d24.7547059!4d46.7076903!16s%2Fg%2F11c5zzbjl6!19sChIJR8SjQIACLz4RSk21ySfkaOI?authuser=0&hl=en&rclk=1
11 https://www.google.com/maps/place/Innova+pharmacy+%7C+%D8%B5%D9%8A%D8%AF%D9%84%D9%8A%D8%A9+%D8%A7%D9%86%D9%88%D9%81%D8%A7%E2%80%AD/data=!4m7!3m6!1s0x3e2f036ce419d2f9:0xa8d4b9d60aeb6fe6!8m2!3d24.6933522!4d46.6967694!16s%2Fg%2F11c5sy6rtb!19sChIJ-dIZ5GwDLz4R5m_rCta51Kg?authuser=0&hl=en&rclk=1
12 https://www.google.com/maps/place/Sahat+Zeina+Pharmacy/data=!4m7!3m6!1s0x3e2f02dd3e89f065:0x746cda82ad5f5a87!8m2!3d24.7197619!4d46.6885397!16s%2Fg%2F1jgly4_44!19sChIJZfCJPt0CLz4Rh1pfrYLabHQ?authuser=0&hl=en&rclk=1
13 https://www.google.com/maps/place/Adama+Pharmacy/data=!4m7!3m6!1s0x3e2f03791491bc67:0xdb13bf5d8474295!8m2!3d24.6854178!4d46.7058238!16s%2Fg%2F11b6gg91xp!19sChIJZ7yRFHkDLz4RlUJH2PU7sQ0?authuser=0&hl=en&rclk=1
14 https://www.google.com/maps/place/Amoon+Pharmacy/data=!4m7!3m6!1s0x3e2f046326585d2d:0xe3d12a54a0a00ae1!8m2!3d24.670881!4d46.7116597!16s%2Fg%2F11csrsxmv2!19sChIJLV1YJmMELz4R4QqgoFQq0eM?authuser=0&hl=en&rclk=1
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.37
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.37
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.37
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.37
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.37
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844 Safari/537.36

DevTools listening on ws://127.0.0.1:63779/devtools/browser/9db93e7d-a894-44c9-bdc4-0f19db238001

DevTools listening on ws://127.0.0.1:63780/devtools/browser/379834e3-0f23-4cca-8aef-1df082a66044

DevTools listening on ws://127.0.0.1:63782/devtools/browser/17823529-4c83-4526-aeff-4769db937406

DevTools listening on ws://127.0.0.1:63781/devtools/browser/0037f5a9-d416-4d57-bdf0-a22cfcf24f99

DevTools listening on ws://127.0.0.1:63783/devtools/browser/17a0e635-fc9c-44f0-a5c7-86ee496d691b

DevTools listening on ws://127.0.0.1:63784/devtools/browser/269f9a26-6dfd-464a-8bef-43c70150c510

DevTools listening on ws://127.0.0.1:63785/devtools/browser/9d3e6970-96b9-4692-87ca-99a9a9b4f270

DevTools listening on ws://127.0.0.1:63789/devtools/browser/371499c4-e97f-4da0-9ad0-ad2d1d137f07

DevTools listening on ws://127.0.0.1:63790/devtools/browser/ce9485ef-52cf-4188-aa0e-a258f9e8e219

DevTools listening on ws://127.0.0.1:63793/devtools/browser/e5cf597b-5a33-451c-9462-e5e9dc207489

DevTools listening on ws://127.0.0.1:63795/devtools/browser/49eb4fc7-6eef-414b-b4dc-7ddc9484a99a

DevTools listening on ws://127.0.0.1:63807/devtools/browser/20a2860a-1066-4b1e-904f-39fef9dfcb74

DevTools listening on ws://127.0.0.1:63808/devtools/browser/6648c38d-5cde-4c24-a28a-fb4044f65e02

DevTools listening on ws://127.0.0.1:63809/devtools/browser/340fe55b-dfa7-4149-b545-55eb8d510603

DevTools listening on ws://127.0.0.1:63823/devtools/browser/2381aa54-c58a-4d59-8093-a1251b5d1af2

DevTools listening on ws://127.0.0.1:63824/devtools/browser/e2baa118-369e-4214-a792-bc023e4b2ed3
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Done: Lemon Pharmacy
Done: صيدلية الجازع 31 Jazea Pharmacy
Done: Lemon pharmacy
Done: Nahdi pharmacy
Done: صيدلية الدواء
Done: صيدلية روز المدينة الطبية
Done: صيدلية الدواء
Done: ALNAHDI PHARMACY
Done: صيدلية الجازع - JAZEA PHARMACY 10
Done: صيدلية الدواء
Done: صيدلية ايرام الطبيه ERAM PHARMACY
Done: Habib Pharmacy صيدلية د. سليمان الحبيب الرئيسية العليا
Done: Nahdi pharmacy | صيدليه النهدى
Done: صيدلية ادم 20 - الملقا - الرياض
Done: صيدلية ادم 35 - السليمانية - الرياض
Done: Boots
Done: صيدلية الدواء
Done: Anwar AlRiyadh Pharmacy
Done: Dana Alseha Pharmacy
Done: LEMON PHARMACY
Done: Aloudah Pharmacy
Done: Zahrat Sami Pharmacy
Done: Lemon Pharmacy | صيدلية ليمون
Done: صيدلية ليمون | Lemon Pharmacy
Done: صيدلية الدواء
Done: Nahdi pharmacy | صيدليه النهدى
Done: صيدلية الدواء
Done: Zahrat Al Rawdah Pharmacy 321 صيدلية زهرة الروضة
Done: Rkn Zahrat Al Rawdah Pharmacy 7
Done: صيدلية الجازع - JAZEA PHARMACY 13
Done: صيدلية الدواء
Done: صيدلية زهرة الروضة 44
Done: Nahdi pharmacy | صيدليه النهدى
Done: Medical Origin Pharmacy - MCO
Done: Hesham Pharmacy
Done: White Pharmacy
Done: Massat al Dawa pharmacy
Done: Zahrat Al Rawdah Pharmacy 18
Done: Innova pharmacy | صيدلية انوفا
Done: Nahdi pharmacy | صيدليه النهدى
Done: صيدلية تاج الدواء ٢٦
Done: Nahdi pharmacy | صيدليه النهدى
Done: Al Malaz National Pharmacy
Done: صيدلية ليمون | Lemon Pharmacy
Done: Nahdi pharmacy | صيدليه النهدى
Done: Orange Pharmacy
Done: صيدلية ليمون | Lemon Pharmacy
Done: صيدلية ليمون | Lemon Pharmacy
Done: صيدلية الدواء
Done: Nahdi pharmacy | صيدليه النهدى
Done: صيدلية الوطن الدوائيه
Done: صيدلية الشافي
Done: Aldawaa Pharmacy
Done: Jazea Pharmacy 6
Done: صيدلية نورا
Done: Kunooz Pharmacy AL OLAYA -1
Done: Dar Al Arab Pharmacy
Done: صيدلية ليمون | Lemon Pharmacy
Done: SHAMS PHARMACY
Done: Kunooz Pharmacy ALMURUJ -2
Done: صيدلية شمس (SHAMS PHARMACY)
Done: Nourapharmacy9 Almalqa
Done: صيدلية الصحة الجيدة (1) العليا good health pharmacy (1) olaya
Done: C Plus Pharmacy
Done: صيدلية الكردي kordy pharmacy
Done: صيدلية الدواء
Done: Nahdi pharmacy | صيدليه النهدى
Done: صيدلية الدواء
Done: Plus two Pharmacy 19 Tajaddawa صيدلية زائد اثنين ١٩ تاج الدوا ‎
Done: Hanger station
Done: ZAHRA AL SHARQ PHARMACY
Done: Innova pharmacy | صيدلية انوفا
Done: SAFE PHARMACY YASMIN
Done: Nahdi pharmacy | صيدليه النهدى
Done: Dorat Lemon Pharmacy t3 smch
Done: LE MÛRE PHARMACIE
Done: صيدلية الدواء
Done: Nahdi pharmacy
Done: صيدلية بيت الأدوية
Done: al dawaa
Done: Nahdi pharmacy
Done: Whites pharmacy
Done: Nahdi pharmacy | صيدليه النهدى
Done: Lemon Pharmacy | صيدلية ليمون
Done: صيدلية ليمون | Lemon Pharmacy
Done: SHAMS PHARMACY
Done: Zahrat Al Rawdah Pharmacy 63 صيدلية زهرة الروضة
Done: Taj ADDAWA Pharmacy 16
Done: Drug Pharmacy Shafi
Done: Adwa Pharmacy
Done: Al Khalifah Pharmacy
Done: Nahdi Pharmacy
Done: Al-Dawaa
Done: Adama Pharmacy
Done: Dr.Wahaf Pharmacy صيدلية د وهف
Done: Innova pharmacy | صيدلية انوفا
Done: Zahrat Al Rawdah Pharmacy 320 صيدلية زهرة الروضة
Done: Balsam Alsaharaa Pharmacy صيدلية بلسم الصحراء
Done: PLUS ONE PHARMACY 6
Done: Zahrat Al Rawdah Pharmacy 3 صيدلية زهرة الروضة
[34880:44560:0217/144517.852:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[2388:28556:0217/144517.855:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
Done: Zahrat Al Rawdah Pharmacy AL ANAYA 24 صيدلية زهرة الروضة العناية الدوائية
Done: Family Basket pharmacy صيدلية سلة العائلة
[34880:44560:0217/144517.938:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
Done: Amoon Pharmacy
Done: Boots pharmacy
Done: TADAWI ATLAS SAGAF PHARMACY
[44828:43992:0217/144518.127:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[44828:28680:0217/144518.277:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[8940:44000:0217/144518.403:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[17960:35536:0217/144518.446:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[17960:8336:0217/144518.476:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
Done: Nahdi pharmacy
Done: نبغاك طيب To Be Well
[40876:11404:0217/144519.507:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[40876:25460:0217/144519.548:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
Done: Ghodaf Pharmacy
[40100:19656:0217/144519.962:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[23740:29148:0217/144520.014:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
Done: Sahat Zeina Pharmacy
Done: Al Badri Pharmacy
[21836:4760:0217/144520.204:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
Done: Alhabib Pharmacy
[29072:8384:0217/144520.365:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[29072:42196:0217/144520.369:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[40272:44508:0217/144520.469:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[40272:16676:0217/144520.473:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
Traceback (most recent call last):
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python311\Lib\site-packages\bose\base_task.py", line 220, in run_task
    result = self.run(driver, data)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_links_task.py", line 265, in run
    new_results = clean(fetched_results, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_links_task.py", line 132, in clean
    new_results = [sort_dict_by_keys(x, keys) for x in new_results]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_links_task.py", line 132, in <listcomp>
    new_results = [sort_dict_by_keys(x, keys) for x in new_results]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_links_task.py", line 89, in sort_dict_by_keys
    new_dict[key] = dictionary[key]
                    ~~~~~~~~~~^^^^^
KeyError: 'price'
Closing Browser
[43472:19912:0217/144522.535:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
Closed Browser
Task Failed! View Final Screenshot at tasks/27/final.png
Task Completed!


so I navigate to the location OUTPIT - GUESS WHAT? NOTING THERE
THEN I REMOVE PRICE, AND OTHER VARIABES (comone, if ti dones't have price use a try{}catch{} or something and let that columns be blank ffs, I see screenshot, 

It also doesn't mention anything about multiple browsers to as I can tell - the pro is a hoax./scame

"tasks/27/final.png" same directory of this agrecious program .  I thought it was cool to start with but its the most unreliable program yet - then how to use git to navigate to the write folder - I just use cmd from the folder address location once manually navigating there... sorry man I used to be your biggest fan, no disappointed. :)#

These other's invariably a problem with you chromdriver.exe - constant have to 1) find correct one on my system / download 3) write over what nonsense is in cC:\Users\jbard\google-maps-scraper-pro-master\build...

ARGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

![image](https://github.com/omkarcloud/google-maps-scraper/assets/13701124/b96b088e-1225-4cc5-94ef-dc102959548c)

**Comment by Chetan11-dev** [comment]
I understand how frustrating it can be to encounter issues with a product in which you've invested, especially when it fails to meet your expectations. I am here to help rectify the situation.

It appears from the logs that you might be using an outdated version of the software. For optimal performance, it's crucial to use the latest version. Please download the Pro Version from this [link](https://www.omkar.cloud/l/google-maps-scraper-pro/), unzip the file, and follow these steps to set up the Pro Version:

1. Navigate to the unzipped folder in your Terminal or Command Prompt and execute the following commands to ensure all dependencies are up to date:
```sh
python -m pip install botasaurus --upgrade
python -m pip install -r requirements.txt
```

2. To start scraping data, run:
```sh
python main.py
```

Furthermore, I'd like to clarify a few points:

- The Pro version requires a one-time payment of $28. You do not need to repurchase for updates. By accessing the pro link sent to your email, you can download the latest version at any time.

- The free version offers scraping few data points, whereas the Pro version allows for scraping of more data points.

- If you require a refund, please let me know. I'm more than willing to process a full refund of your complete purchase.

- You need Node.js to run the updated version, which you can download from https://nodejs.org/en. After installing Node.js, please restart your system to complete the setup.

I am here to support you in resolving these issues and to answer any further questions you might have. Ensuring your satisfaction is our top priority.

Thank you for your understanding,
Chetan

**Comment by 007-JB** [comment]
Hello,

I apologize if my previous message came across as informal or unprofessional. I truly value the work you're doing here, and it's precisely because I rely on it so much that I feel disappointed when things don't go as planned. My intention was not to undermine or disrespect your efforts. Your quick response to my concerns was impressive and greatly appreciated.

I'm keen to give this another try and want to express my gratitude for your swift and effective communication. Your dedication makes all the difference, and I believe the contributions ($  I've made is worthwhile. Please know that I'm fully supportive of this project and look forward to seeing how it progresses. Let's continue to work together to overcome any challenges that may arise.

Thank you for your understanding and patience. Don't lose faith in me as a contributor to this community.

Best regards,

007-JB

**Comment by Chetan11-dev** [comment]
Hello 007-JB,

Thank you for your message and understanding. There's absolutely no need to apologize; we value your honest feedback as it helps us improve. It's great to hear you're willing to give this another try. Your support is crucial to us, and we're committed to overcoming challenges together.

Please rest assured that your input is always welcome, and we view every challenge as an opportunity to grow and improve.

Best,
Chetan

**Comment by 007-JB** [comment]
you da man/person (not sure RE gender - not that it matters just don't want
to offend either way.
K giving it a go wihs me luc,
Chetan guys name- so you do man"
:)

**Comment by Chetan11-dev** [comment]
Thanks, I really appreciate the support. And  I am a man. 😊
