### ISSUE TITLE
distance filtering and searching more accurate

### ISSUE THREAD

**Issue by catspyder** [omkarcloud/google-maps-scraper#131]
so can u filter results by distance .
can u search by your current location not just the city

**Comment by Chetan11-dev** [comment]
I'm having difficulty understanding your question. Could you please provide more detail or elaborate further, probably with an example?

**Comment by mailbau** [comment]
maybe he meant is there a way to search based on our current location, for example restaurants near me? and I also wanna ask is it possible to return latitude and longitude (coordinates) of the results?

**Comment by Chetan11-dev** [comment]
latitude and longitude are provided in Pro Version.
