### ISSUE TITLE
I am getting strange characters in the results 

### ISSUE THREAD

**Issue by Gentl3man** [omkarcloud/google-maps-scraper#157]
When running the scraper some fields on the csv appear broken picture bellow.
![image](https://github.com/omkarcloud/google-maps-scraper/assets/73713358/1adfb8fd-85e8-4290-b87b-2690e9247d19)

The text here seems that its missing or the scraper fails to get the correct text, or it fails to translate the text in to UTF-8.
As you can see on the image the description of the first place is corrupted:
 ```
 ***n*rvino è*i* lu*go*i**a** **r**li***p*s*i******di v*no**i**u*****!****n*s*ra*****z**** escl***v* ** v*n* ita*ia*i** *n*e*******al* t**a*p*tta nel*no*t*o nego*** *n **A DA*****3 ** *****a*o**O*fria***una*va**a*ga*ma d* *t***et*e **r **dd*s*a***ogni **st** d*i *i*i c*assici * **ell****ù *s*l**iv*:*****s*r* **ss** ****chi******l*ci***ti*****ui**e**n*o c****a*******c*e*iona*e**ualit*.**n***re,*i****t***espe**i ** v*** s**o s*m**e*a******s**i*** *e* con****i*e **pporto nell* sce*** ****a b****g**a***rf*t****e* ogn***cc*s**ne* M* n** **nisc**qui, Si***rvin**è a**he u* r****r**** **ve*potrai d*g*s*ar*** nost***v*ni***comp***a*i da*****i**te*ze c***n*r**,*p*r **'*s*e**enza **n**r*al* *n*ca."
 ```
 Is this an known issue or i messed up the set up on my computer?

**Comment by Chetan11-dev** [comment]
Free versions shows only a limited set of data points, the fields are hidden with "*". To access additional datapoints, you will need to upgrade to the Pro Version.
Let me know if you further questions!
Happy to help!

**Comment by Gentl3man** [comment]
but you still get these data, with a small modification in the code i can get it, you scrape the description but you just dont show it, it looks more like a bug than a feature

**Comment by Chetan11-dev** [comment]
It's a feature.
