### ISSUE TITLE
UTF-8 Encoding for foreign characters

### ISSUE THREAD

**Issue by xbiggyl** [omkarcloud/google-maps-scraper#16]
First of all thanks for creating this scraper.

I am able to scrape google maps but I am facing an issue when exporting results that include foreign characters in them.

For example, this is how one of the extracted addresses appears on google maps:

**Teşvikiye, 34659 Şişli/İstanbul, Türkiye**

And this is the same address in the output of the scraper (both json and csv):

**TeÅŸvikiye, 34659 ÅžiÅŸli/Ä°stanbul, ØªØ±ÙƒÙŠØ§**

I believe it's an encoding issue and hopefully you might be able to find an easy solution.

Cheers

**Comment by Chetan11-dev** [comment]
If someone

**Comment by xbiggyl** [comment]
Were you able to find any solution for that?

**Comment by Chetan11-dev** [comment]
No
