### ISSUE TITLE
Bug failed to find document

### ISSUE THREAD

**Issue by dlzdrgdr** [omkarcloud/google-maps-scraper#166]
It seems to have trouble scrolling. Any idea?

![Capture d'écran 2024-05-15 003806](https://github.com/omkarcloud/google-maps-scraper/assets/92653430/b8cf29b3-474f-4322-8bfb-64e648da6f29)

**Comment by Chetan11-dev** [comment]
Don't worry about it, we automatically retry upto 3 times, in case of any error.
