### ISSUE TITLE
Issue with Pro Version of Google Maps Scraper: Non-functional despite Successful Experience with Free Version

### ISSUE THREAD

**Issue by alariordas** [omkarcloud/google-maps-scraper#17]
I have encountered a critical issue while using the Pro version of the Google Maps scraper from the GitHub repository. In my experience, the free version of the scraper has been working seamlessly, providing accurate and relevant data. However, the professional version seems to be non-functional, failing to deliver the expected results. To ensure it wasn't an isolated incident, I meticulously tested the Pro version on two different computers, but unfortunately, the outcome remained the same – no data was scraped. To assist with identifying the root cause, I have attached a log file, hoping that the community can provide insights and help resolve this problem promptly. Your prompt assistance in rectifying this matter would be highly appreciated.

[error.log](https://github.com/omkarcloud/google-maps-scraper/files/12130406/error.log)
![final](https://github.com/omkarcloud/google-maps-scraper/assets/80034759/7d38504a-b3a0-4d24-ada0-684697600d06)

**Comment by Chetan11-dev** [comment]
Fixed and sent the updated version
