### ISSUE TITLE
Is there any way to use wiyhout api.

### ISSUE THREAD

**Issue by babynew** [omkarcloud/google-maps-scraper#172]
Is there any way to use wiyhout api. any one have code that directly call the python code as previous versions have?

**Comment by Chetan11-dev** [comment]
Create a test.py file in root with following contents
```python
from src.scraper import scrape_places
print(scrape_places({'query': 'Web Developers   in Bangalore', 'max': 1, 'lang': 'en', 'geo_coordinates': '', 'zoom': 14, 'links':[]}))
```
Then run it.

**Comment by Chetan11-dev** [comment]
To run multiple queries do like 
```python
from src.scraper import scrape_places
print(scrape_places([
{'query': 'Web Developers in Bangalore', 'max': 1, 'lang': 'en', 'geo_coordinates': '', 'zoom': 14, 'links':[]},
{'query': 'Web Developers in Delhi', 'max': 1, 'lang': 'en', 'geo_coordinates': '', 'zoom': 14, 'links':[]},
], parallel=5, cache=True,
# proxy=['proxy1', 'proxy2']
))
```

**Comment by canonrock16** [comment]
Is there any way to get 'detailed reviews' without running server?
I tried below code, but couldn't get 'detailed reviews'. There was only 'featured_reviews'.

> To run multiple queries do like
> 
> ```python
> from src.scraper import scrape_places
> print(scrape_places([
> {'query': 'Web Developers in Bangalore', 'max': 1, 'lang': 'en', 'geo_coordinates': '', 'zoom': None, 'links':[]},
> {'query': 'Web Developers in Delhi', 'max': 1, 'lang': 'en', 'geo_coordinates': '', 'zoom': None, 'links':[]},
> ], parallel=5, cache=True,
> # proxy=['proxy1', 'proxy2'] # <--- optional
> ))
> ```

**Comment by Chetan11-dev** [comment]
Okay, for that read src/gmaps.py, so basically you need to a merge with reviews similar to that in the scraping function in src/gmaps.py.

**Comment by canonrock16** [comment]
Thank you!
