### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Iamtheoldman** [omkarcloud/google-maps-scraper#174]
google-maps-scraper-pro-master/docker-compose.yaml: `version` is obsolete 
[+] Building 2.1s (11/11) FINISHED                                                                                 docker:desktop-linux
 => [bot-1 internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 291B                                                                                               0.0s
 => [bot-1 internal] load metadata for docker.io/ultrafunk/undetected-chromedriver:106                                             0.4s
 => [bot-1 internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                                    0.0s
 => [bot-1 internal] load build context                                                                                            0.0s
 => => transferring context: 32.77kB                                                                                               0.0s
 => [bot-1 1/6] FROM docker.io/ultrafunk/undetected-chromedriver:106@sha256:a165c9809124d2b2221e57d002c9b0bbc8dff94e964ea44a5a0c9  0.0s
 => CACHED [bot-1 2/6] COPY requirements.txt .                                                                                     0.0s
 => CACHED [bot-1 3/6] RUN python -m pip install  -r requirements.txt                                                              0.0s
 => CACHED [bot-1 4/6] RUN mkdir app                                                                                               0.0s
 => CACHED [bot-1 5/6] WORKDIR /app                                                                                                0.0s
 => [bot-1 6/6] COPY . /app                                                                                                        1.0s
 => [bot-1] exporting to image                                                                                                     0.5s
 => => exporting layers                                                                                                            0.4s
 => => writing image sha256:c3072aea0b6f8d6c87053a0aa58c4f6c701cb15f60ba044117724ad88db605e5                                       0.0s
 => => naming to docker.io/library/google-maps-scraper-pro-master-bot-1                                                            0.0s
WARN[0000] /Users/dameonjensen/Desktop/google-maps-scraper-pro-master/docker-compose.yaml: `version` is obsolete 
[+] Running 1/0
 ⠋ Container google-maps-scraper-pro-master-bot-1-1                                                                                     [+] Running 2/2 Recreate0.1s 
 ✔ Container google-maps-scraper-pro-master-bot-1-1                                                                                                     Recreated0.1s 
 ! bot-1 The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
Attaching to bot-1-1
bot-1-1  | running: python main.py
bot-1-1  | running keepUpScreen()
bot-1-1  | Task Started
bot-1-1  | Running in Docker, So adding sandbox arguments
bot-1-1  | Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844 Safari/537.36
bot-1-1  | Traceback (most recent call last):
bot-1-1  |   File "/app/main.py", line 16, in <module>
bot-1-1  |     launch_tasks(*tasks_to_be_run)
bot-1-1  |   File "/usr/local/lib/python3.10/site-packages/bose/launch_tasks.py", line 54, in launch_tasks
bot-1-1  |     current_output = task.begin_task(current_data, task_config)
bot-1-1  |   File "/usr/local/lib/python3.10/site-packages/bose/base_task.py", line 249, in begin_task
bot-1-1  |     final = run_task(False, 0)
bot-1-1  |   File "/usr/local/lib/python3.10/site-packages/bose/base_task.py", line 196, in run_task
bot-1-1  |     driver = self.create_driver(config)
bot-1-1  |   File "/usr/local/lib/python3.10/site-packages/bose/base_task.py", line 73, in create_driver
bot-1-1  |     driver =  create_driver(config)
bot-1-1  |   File "/usr/local/lib/python3.10/site-packages/bose/create_driver.py", line 288, in create_driver
bot-1-1  |     driver = retry_if_is_error(
bot-1-1  |   File "/usr/local/lib/python3.10/site-packages/bose/utils.py", line 88, in retry_if_is_error
bot-1-1  |     raise e
bot-1-1  |   File "/usr/local/lib/python3.10/site-packages/bose/utils.py", line 81, in retry_if_is_error
bot-1-1  |     created_result = func()
bot-1-1  |   File "/usr/local/lib/python3.10/site-packages/bose/create_driver.py", line 277, in run
bot-1-1  |     driver = BoseDriver(
bot-1-1  |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
bot-1-1  |     super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
bot-1-1  |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
bot-1-1  |     self.service.start()
bot-1-1  |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 71, in start
bot-1-1  |     self.process = subprocess.Popen(cmd, env=self.env,
bot-1-1  |   File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
bot-1-1  |     self._execute_child(args, executable, preexec_fn, close_fds,
bot-1-1  |   File "/usr/local/lib/python3.10/subprocess.py", line 1847, in _execute_child
bot-1-1  |     raise child_exception_type(errno_num, err_msg, err_filename)
bot-1-1  | OSError: [Errno 8] Exec format error: '/app/build/chromedriver'
bot-1-1 exited with code 1

**Comment by Chetan11-dev** [comment]
Run
python -m pip install --upgrade pip
python -m pip install bota botasaurus botasaurus_api botasaurus_driver bota botasaurus-proxy-authentication botasaurus_server --upgrade
Reclone and install repository
docker-compose build && docker-compose up

**Comment by Iamtheoldman** [comment]
I noticed the webdriver is not working do I have to repeat this?

**Comment by Chetan11-dev** [comment]
yes

**Comment by Iamtheoldman** [comment]
issue still not working. Followed steps are as told

**Comment by Chetan11-dev** [comment]
- Kindly send email to chetan@omkar.cloud so I can the last python node version dated 4th October
- If all you want is to run in Server, I recommend running in Google Cloud by following https://github.com/omkarcloud/botasaurus?tab=readme-ov-file#how-to-run-scraper-in-virtual-machine, you won't face any issues. 
- Docker has been unreliable to run.
