### ISSUE TITLE
ModuleNotFoundError: No module named 'botasaurus.browser' during dependency installation

### ISSUE THREAD

**Issue by dawidmatyjasik** [omkarcloud/google-maps-scraper#176]
**Description:**

I encountered an error when attempting to install dependencies using the command `python3 run.py install`. The error traceback indicates that a module named 'botasaurus.browser' cannot be found. 

**Steps to Reproduce:**

1. Clone the repository.
2. Navigate to the project directory.
3. Run the command: `python3 -m pip install -r requirements.txt && python3 run.py install`.

**Expected Behavior:**

Dependencies should be installed without any errors.

**Actual Behavior:**

The following error occurs:

```markdown
Traceback (most recent call last):
File "/Users/dawidspisak/Documents/onlinemasters/google-api-2/run.py", line 1, in <module>
import backend.scrapers
File "/Users/dawidspisak/Documents/onlinemasters/google-api-2/backend/scrapers.py", line 2, in <module>
from src.gmaps import get_places
File "/Users/dawidspisak/Documents/onlinemasters/google-api-2/src/gmaps.py", line 1, in <module>
from src import scraper
File "/Users/dawidspisak/Documents/onlinemasters/google-api-2/src/scraper.py", line 9, in <module>
from botasaurus.browser import Driver, browser, AsyncQueueResult, Wait, DetachedElementException
ModuleNotFoundError: No module named 'botasaurus.browser'
```

**Environment:**

- OS: Sonoma 14.5 - Apple M1 
- Python version: 3.12.1

**Additional Information:**

It seems like the module 'botasaurus.browser' is not installed or is missing from the project's dependencies. Please provide guidance on how to resolve this issue or update the installation instructions to include this dependency.

Thank you!

**Comment by Chetan11-dev** [comment]
Kindly run 
python -m pip install bota botasaurus botasaurus_api botasaurus-requests botasaurus_driver bota botasaurus-proxy-authentication botasaurus_server --upgrade
