### ISSUE TITLE
Can we use Proxies with the Bose framework?

### ISSUE THREAD

**Issue by geniecode1** [omkarcloud/google-maps-scraper#18]
I've checked the documentation but there wasn't an explicit explication of how to integrate proxies with the Bose framework.
Is this possible? If yes, can you explain how it should be done, please?

**Comment by Chetan11-dev** [comment]
We kindly request you to run the following command to update the dependencies:
```
python -m pip install bose --upgrade
```

and see follwing example to learn how to use proxy:

```python 
class Task(BaseTask):
    browser_config = BrowserConfig(
        proxy = "http://lum-customer-hl_1b230841-zone-MYZONE:MYPW@zproxy.lum-superproxy.io:22225"
    )
```
