### ISSUE TITLE
Support Chinese

### ISSUE THREAD

**Issue by Oliver0804** [omkarcloud/google-maps-scraper#192]
The programme is great, 
but using the output only outputs English CSV.... 
Can you add Chinese google map output, thanks.

**Comment by Chetan11-dev** [comment]
Use chinese language, and change download setting and disable english conversion
<img width="778" alt="Screenshot 2024-08-09 at 10 39 11 AM" src="https://github.com/user-attachments/assets/2c0ea722-f6b2-4df7-b65a-19f1b2e81a17">

**Comment by Oliver0804** [comment]
![截圖 2024-08-09 晚上9 03 18](https://github.com/user-attachments/assets/db9452ce-71fc-4a7a-85c0-a93e04065224)
Yes, I have noticed this feature, but the vast majority is still in English, with only a very small part in Chinese.

**Comment by Chetan11-dev** [comment]
We give you direct results we get from gmaps, if there are not in chineses, then results will the same.

**Comment by Oliver0804** [comment]
> We give you direct results we get from gmaps, if there are not in chineses, then results will the same.

"I was originally using hl=en, but if I change it to zh-TW, I believe I can successfully obtain the correct Chinese version.
![截圖 2024-08-09 晚上9 54 22](https://github.com/user-attachments/assets/55679899-4528-4cbd-b0c8-ddd2670581fc)

```
https://www.google.com/maps/place/%E9%8A%93%E5%8F%8B%E9%9B%BB%E6%B1%A0-%E6%B9%AF%E6%B7%BA%E9%9B%BB%E6%B1%A0%E5%B0%88%E8%B3%A3%E5%BA%97/data=!4m7!3m6!1s0x34681f2166960915:0xc64090935296478a!8m2!3d24.9782994!4d121.3036157!16s%2Fg%2F11bwn4dz45!19sChIJFQmWZiEfaDQRikeWUpOQQMY?authuser=0&hl=en&rclk=1
```

```
https://www.google.com/maps/place/%E9%8A%93%E5%8F%8B%E9%9B%BB%E6%B1%A0-%E6%B9%AF%E6%B7%BA%E9%9B%BB%E6%B1%A0%E5%B0%88%E8%B3%A3%E5%BA%97/data=!4m7!3m6!1s0x34681f2166960915:0xc64090935296478a!8m2!3d24.9782994!4d121.3036157!16s%2Fg%2F11bwn4dz45!19sChIJFQmWZiEfaDQRikeWUpOQQMY?authuser=0&hl=zh-TW&rclk=1
```

**Comment by Chetan11-dev** [comment]
Open backend/scrapers.py and add following line to use zh-TW. 
<img width="783" alt="Screenshot 2024-08-10 at 1 27 25 PM" src="https://github.com/user-attachments/assets/bbbc6c6a-2f56-414a-884d-287b52753b97">

**Comment by Oliver0804** [comment]
You are my god, the test was successful, thank you so much.
