### ISSUE TITLE
Requirements install not working

### ISSUE THREAD

**Issue by aHagouel** [omkarcloud/google-maps-scraper#196]
Ran the onboarding steps but got this error message when trying to run:
 
    from botasaurus_server.server import Server
ModuleNotFoundError: No module named 'botasaurus_server'

Running on M1 Mac

**Comment by Chetan11-dev** [comment]
please run
python3 -m pip install bota botasaurus botasaurus-api botasaurus-requests botasaurus-driver bota botasaurus-proxy-authentication botasaurus-server --upgrade
