### ISSUE TITLE
All Tasks Fail 

### ISSUE THREAD

**Issue by thatdudeagain** [omkarcloud/google-maps-scraper#198]
I've installed the software without any errors, and the browser page opens fine. However, despite setting various search criteria, all tasks fail in less than a second. The only task that remains in a "running" or "in progress" state is the one named "All Tasks." I let it run for 28 hours, but it produced no results.

I even tried to replicate the search from the demonstration (e.g., "web developers in Bangalore") but encountered the same issue.

Has anyone experienced this problem?

I'm running this in a virtual environment (venv) inside a local Hyper-V virtual machine.

**Comment by OneKrown** [comment]
What browser are you using?

**Comment by Chetan11-dev** [comment]
Don't use venv with (venv) inside a local Hyper-V virtual machine, instead either 
use gitpod: https://github.com/omkarcloud/google-maps-scraper/blob/master/advanced.md#-i-dont-have-python-or-im-facing-errors-when-setting-up-the-scraper-on-my-pc-how-to-solve-it
run in gcloud: https://github.com/omkarcloud/botasaurus#how-to-run-scraper-in-virtual-machine
PS: could you share errors in terminal?

**Comment by thatdudeagain** [comment]
I was using Firefox, but I tested it on Chrome based on OneKrown suggestion, and everything works fine.

Chetan11-dev - Thanks for your recommendation; I will look into it later.
