### ISSUE TITLE
eamils 

### ISSUE THREAD

**Issue by kikar92** [omkarcloud/google-maps-scraper#2]
can you please add email too

**Comment by Chetan11-dev** [comment]
Correct me if I am wrong but Google maps does not to list emails. So, only option you have is to use https://rapidapi.com/letscrape-6bRBa3QguO5/api/website-contacts-scraper/ to scrape emails from the website.

**Comment by kikar92** [comment]
> orrect me if I am wrong but Google maps does not to list emails.

i didn't know that Thank you also id odon't know how to use the API

**Comment by Chetan11-dev** [comment]
I hope you know coding, You need to create an account on RapidApi and use their Api to get them.
