### ISSUE TITLE
Program not running because of  a missing driver

### ISSUE THREAD

**Issue by Wolfvaudou** [omkarcloud/google-maps-scraper#20]
When I run main.py, I got this message:
 'WARNING:root:Can not find chromedriver for currently installed chrome version.' 
making the script crashes. Tried it under Windows and Ubuntu on 3 differents PC, same issue.

**Comment by Chetan11-dev** [comment]
@TomerGamerTV, 
Temporary Bug due on of the dependency of Bose chromedriver-autoinstaller. The fix is to:
1. Go to https://googlechromelabs.github.io/chrome-for-testing/#stable and download your version
2. Place it in build/ folder
3. Run python main.py and program should run successfuly.

**Comment by Wolfvaudou** [comment]
Still not working, I take linux64 version of chromedriver, unzip it in build, renamed it into chromedriver (after deleting the one already there) then executed main.py but it didnt work and deleted the chromedriver file.

**Comment by Chetan11-dev** [comment]
Weird, share error log

**Comment by Wolfvaudou** [comment]
It was my bad. I meesed up with the unzipping and ended up with a chromedriver **folder** in build. My last little pb is, despite I have google-version-stable installed, he stills use mozilla as browser.

**Comment by Chetan11-dev** [comment]
All's well that end well!

**Comment by 007-JB** [comment]
Awesome - had same issue but resolved same way advised as above - pro version totally worth it man legend yeah!! :) 👍

**Comment by fabioselau077** [comment]
> Temporary Bug due on of the dependency of Bose `chromedriver-autoinstaller`. The fix is to:
> 
> 1. Go to https://googlechromelabs.github.io/chrome-for-testing/#stable and download "chrome driver" based on your chrome version.
> 2. Extract the zip file
> 3. Please place the "chromedriver" file (or "chromedriver.exe" if you are using Windows) directly into the build/ folder. Make sure you're not placing the entire folder but only the chrome driver file itself.
> 4. Run python main.py and program should run successfuly.
> 
> EDIT: Updated Instructions for Clarity

not working here... error after start main.py
<img width="946" alt="image" src="https://github.com/omkarcloud/google-maps-scraper/assets/57275833/c227ff4b-082f-4496-809d-e6de72be00c5">

my build folder
<img width="755" alt="image" src="https://github.com/omkarcloud/google-maps-scraper/assets/57275833/6bdb5693-67dd-4f82-af71-ba7f004d59a0">


In macOS working without problems, but in Ubuntu not working, same time one diff error

**Comment by fabioselau077** [comment]
Resolved. I've been trying to solve it since yesterday and I've solved it now.
You also need to have google-chrome installed, not just chromedriver.
That solved:
```
apt update && apt install wget
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

apt install ./google-chrome-stable_current_amd64.deb
```

Find this solution in one [question](https://stackoverflow.com/questions/76867458/cannot-find-chrome-binary-while-chromedriver-exists) in stackoverflow
