### ISSUE TITLE
Cities in the country

### ISSUE THREAD

**Issue by derekemm** [omkarcloud/google-maps-scraper#218]
Hello,

There are missing cities or regions in the country we specified in the search criteria. Is there a way to fix this?

**Comment by Chetan11-dev** [comment]
Use Bulk Edit
<img width="757" alt="Screenshot 2024-11-06 at 5 54 45 PM" src="https://github.com/user-attachments/assets/05275c6c-3418-4e67-aaae-592c0ec726d1">

<img width="749" alt="Screenshot 2024-11-06 at 5 55 03 PM" src="https://github.com/user-attachments/assets/074e4ad6-8c5e-449f-b8ca-bb934f0e2c42">
