### ISSUE TITLE
Query loop

### ISSUE THREAD

**Issue by ander-son-almeida** [omkarcloud/google-maps-scraper#22]
Hey guys!

Congratulations on the incredible work. I have a trivial question, I want to perform a for loop, in which the query inside the config.py file is updated. For example: read a list of 5 cities, and for each of them, I want to return the results of schools and restaurants. Do you have any suggestions on how to do this?

**Comment by Chetan11-dev** [comment]
Thanks, 
Also you need to write fairly simple python code in "scrape_google_maps_links_task.py".
