### ISSUE TITLE
Detailed Review // "Published At Date" is always empty

### ISSUE THREAD

**Issue by tobilindner** [omkarcloud/google-maps-scraper#220]
Hi.

I am using the newest version (download and installation on 2024-11-07).

If I active "Detailed Reviews", the column "Published At Date" is always empty.
"Published At" in text format is working, but date format is empty.

On "Featured Reviews" everything works fine.

Please fix.
Thanks in advance.
Tobi

**Comment by Chetan11-dev** [comment]
That data point is only available for english language, as we compute it.

**Comment by tobilindner** [comment]
Hi @Chetan11-dev.

Thanks for the quick response.

I did not get it. On "Featured Reviews" is is working - even I change the language to not be english. See screenshot with German language.

Best,
Tobi

![grafik](https://github.com/user-attachments/assets/1e07fa43-6c1a-4d77-901e-94b80ef189e9)

**Comment by Chetan11-dev** [comment]
detailed reviews date is derived fro, text field, as such format data is not provided.

**Comment by Chetan11-dev** [comment]
technically not possible
