### ISSUE TITLE
Detailed Review // "Response From Owner Date" is missing

### ISSUE THREAD

**Issue by tobilindner** [omkarcloud/google-maps-scraper#221]
Hi.

I am using the newest version (download and installation on 2024-11-07).

If I active "Detailed Reviews", the column "Response From Owner Date" is empty (or actually "null" in Excel export).
"Response From Owner Ago" in text format is working, but date format is empty.

On "Featured Reviews" everything works fine.

Please fix.
Thanks in advance.
Tobi

**Comment by Chetan11-dev** [comment]
That data point is only available for english language, as we compute it from Response From Owner Ago
