### ISSUE TITLE
Tips and recommendations for leaving the library permanently installed on https://cloud.linode.com/linodes

### ISSUE THREAD

**Issue by devmilitia** [omkarcloud/google-maps-scraper#225]
Hi partners,
Any manual or documentation to place permanent deploy of the script in cloud environment like https://cloud.linode.com/linodes
Best Regards

**Comment by Chetan11-dev** [comment]
Due to move to desktop app, we removed python code, so this won't be possible. Don't worry can can complete 1000s of searches in a Day.
