### ISSUE TITLE
No Results

### ISSUE THREAD

**Issue by rvschaffer** [omkarcloud/google-maps-scraper#227]
Hi, 
I'm getting "No results" for all new tasks, independently on the task query/search text.
Is there a way to troubleshoot this issue?
I'm afraid Google Maps is somehow blocking me from scraping, or something.

**Comment by Chetan11-dev** [comment]
- You have chrome right?
- Does https://www.google.com/maps/place/SeekNEO/data=!4m7!3m6!1s0x3bae13ac4bcc6641:0x1bf48a7dee3d5a51!8m2!3d12.9846754!4d77.5480382!16s%2Fg%2F11g2338zrl!19sChIJQWbMS6wTrjsRUVo97n2K9Bs?authuser=0&hl=en&rclk=1
as search input works?
