### ISSUE TITLE
scrapping with exact name and city

### ISSUE THREAD

**Issue by y-aoub** [omkarcloud/google-maps-scraper#23]
Hello, thank you for you efforts ! It's a great job what you've done :) 
I had some issues while trying to scrape information using "exact_name" + "city" (below the debug screenshot). It seems that it works only when maps is showing a list of results. Do you have an idea how to fix this ? 

thank you again ! 

![final](https://github.com/omkarcloud/google-maps-scraper/assets/71386458/024b9970-8248-42d6-af75-3c852a461b40)

**Comment by Chetan11-dev** [comment]
Yes, it can only scrape list. At this point of time, I'm not planning to add this feature.

However, should more users express this problem, I will surely reconsider my decision.

Thank you for your understanding.
Chetan

**Comment by Chetan11-dev** [comment]
Fixed in latest Version
