### ISSUE TITLE
Output language & Null price_range

### ISSUE THREAD

**Issue by MoRaouf** [omkarcloud/google-maps-scraper#24]
When I search for a query, the return output contains data in different languages (e.g. Arabic). How can I set the language of all the output to be only English?
Also, the returned field `price_range` is always `Null`, probably needs fixing as Google sets price ranges for every location.

**Comment by Chetan11-dev** [comment]
1. Use a vpn like ProtonVpn and connect to USA IP to get results in english.
2. Give me an example query where you get the price_range null instead of price range along with screenshot of the place.

**Comment by MoRaouf** [comment]
Thank you for your quick response. The VPN did work & results are all in English now.
For the price range, still results are `Null`, check the attached screenshot.
![Screenshot 2023-08-14 190342](https://github.com/omkarcloud/google-maps-scraper/assets/78295016/9439b63f-ab13-473b-a989-c2725ba3c386)

**Comment by Chetan11-dev** [comment]
Price Range not given in google maps
![Screenshot (531)](https://github.com/omkarcloud/google-maps-scraper/assets/53407137/4513c319-9ff2-4abe-b9ac-9283894afc63)

**Comment by MoRaouf** [comment]
Actually, some places do indicate `price_range` through a "$" sign. As defined in the API docs, the `price_range` is from 0 to 4, hence they **sometimes** show it on Google maps (check the screenshot) but mostly they don't. Thanks a lot though for the great tool you provided us, your work is very much appreciated.

![Screenshot 2023-08-14 220103](https://github.com/omkarcloud/google-maps-scraper/assets/78295016/06ef197a-7b37-4524-a9df-f84ac0ef4d03)
