### ISSUE TITLE
If there is no search results found in the query It stuck in DevTools listening and to going to next query

### ISSUE THREAD

**Issue by karim-Abd-El-Hameed** [omkarcloud/google-maps-scraper#27]
Task Started
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.37

DevTools listening on ws://127.0.0.1:63890/devtools/browser/5f7df4b4-7a45-4baa-b576-759cb7613322
Launched Browser

**Comment by Chetan11-dev** [comment]
Hello Karim,
Thank you for contacting me. Regrettably due to my tight schedule, I'm unable to assist with that.

However, I encourage you to hire a freelancer specializing in webscraping/selenium/python from upwork to fix your problem.

Thank you for your understanding,

**Comment by Chetan11-dev** [comment]
Could you share query for which this behavior happens, I was unable to reproduce them
