### ISSUE TITLE
Queries not working

### ISSUE THREAD

**Issue by speenoo** [omkarcloud/google-maps-scraper#36]
### Description

Queries not working for specific requests such as max/min reviews. Sorting is not working either for me

### Steps to Reproduce

No reproduction steps. Off the bat it has not been working for me.

**Expected behavior:** Only pull businesses with more reviews than 5 and less than 20

**Actual behavior:** Pulls businesses indiscriminately 

**Reproduces how often:** 100%

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by Chetan11-dev** [comment]
Thanks for informing, Fixed in latest version, Please use it.
