### ISSUE TITLE
user the Options of selenium driver directly

### ISSUE THREAD

**Issue by amkahal88** [omkarcloud/google-maps-scraper#40]
Dear, 
the scraper is working great, except for the language, this is my browser_config:
 ```
 browser_config = BrowserConfig(
        headless=True,
        lang="en"

    )
```

i tried also:

```
browser_config = BrowserConfig(
        headless=True,
        lang="en-GB"

    )
```

still getting the results like the business category in German (since i'm in Germany)

can i just pass `accept-lang="en-GB"` as an argument to the driver directly in a way ?

**Comment by Chetan11-dev** [comment]
You have 2 Option:
1. Use Free ProtonVpn to connect to US Ip and Scrape
2. Override create_driver in BaseTask and return a Driver with Options.
