### ISSUE TITLE
get latitude and longitude

### ISSUE THREAD

**Issue by basheer-shahrour** [omkarcloud/google-maps-scraper#42]
can I get location data ?

**Comment by admiral504** [comment]
> can I get location data ?

The location data is already included in the output. Each row in the output will have a coordinates column that contains the latitude and longitude for that data point. The coordinates are stored as a dictionary with the keys 'latitude' and 'longitude'. For example:

{'latitude': 10.7322283, 'longitude': 106.6896905}























coordinates
{'latitude': 10.7322283, 'longitude': 106.6896905}
