### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by xer0xde** [omkarcloud/google-maps-scraper#64]
When I try to launch the Crawler, it gives me an Error "'NoneType' object is not subscriptable"

thats my main.py
from src.gmaps import Gmaps
star_it = '''Love It? Star It! ⭐ https://github.com/omkarcloud/google-maps-scraper/'''

queries = [

   "Hotels",
   "Cafés",
   "Bekleidungsgeschäfte",
   "Elektronikläden",
   "Buchhandlungen",
   "Blumengeschäfte",
   "Optiker",
   "Gesundheitszentren",
   "Banken",
   "Nagelstudios",
   "Computerreparaturdienste",
   "Reisebüros",
   "Kunstgalerien",
   "Schuhgeschäfte",
   "Möbelgeschäfte",
   "Sportgeschäfte",
   "Juweliere",
   "Musikgeschäfte",
   "Tierhandlungen",
   "Fotostudios",
   "Fast-Food-Restaurants",
   "Feinkostläden",
   "Kinderbetreuungsdienste",
   "Yoga-Studios",
   "Kosmetikstudios",
   "Fahrradgeschäfte",
   "Geschenkeläden",
   "Elektriker",
   "Maler",
   "Installateure",
   "Baumärkte",
   "Augenoptiker",
   "Elektronikmärkte",
   "Physiotherapeuten",
   "Spielzeugläden",
   "Architekten",
   "Druckereien",
   "Gebrauchtwagenhändler",
   "Sonnenstudios",
   "Nagelstudios",
   "Weinhandlungen",
   "Spielhallen",
   "Frisöre",
   "Elektrogeschäfte",
   "Geschenkeshops",
   "Reiseveranstalter",
   "Bäckereien",
   "Schönheitssalons",
   "Bauunternehmen",
   "Tierpflegedienste",
   "Gesundheitspraxen",
   "Gemischtwarenläden",
   "Handy-Geschäfte",
   "Fahrschulen",
   "Handwerker",
   "Goldschmiede"
   "Tattoo-Studios",
   "Outdoor-Ausrüstungsgeschäfte",
   "Konditoreien",
   "Brautgeschäfte",
   "Mietwagenfirmen",
   "Karaoke-Bars",
   "Haushaltswarengeschäfte",
   "Floristen",
   "Imbissstände",
   "Haustierbetreuungsdienste",
   "Kunsthandwerksläden",
   "Wäschereien",
   "Tanzstudios",
   "Second-Hand-Läden",
   "Gourmet-Restaurants",
   "Schwimmbäder",
   "Veranstaltungsorte für Live-Musik",
   "Liquor Stores",
   "Gartenbauunternehmen",
   "Tauchgeschäfte",
   "Uhrengeschäfte",
   "Radsportgeschäfte",
   "Therapeuten",
   "Ski-Shops",
   "Sushi-Restaurants",
   "Fensterputzer",
   "Schlüsseldienste",
   "Cocktailbars",
   "Pizzerien",
   "Handtaschengeschäfte",
   "Ballettschulen",
   "Teppichreinigungsdienste",
   "Flughafen-Taxis",
   "Fotolabors",
   "Heimwerkerläden",
   "Tattoo-Studios",
   "Outdoor-Ausrüstungsgeschäfte",
   "Konditoreien",
   "Brautgeschäfte",
   "Mietwagenfirmen",
   "Karaoke-Bars",
   "Haushaltswarengeschäfte",
   "Floristen",
   "Imbissstände",
   "Haustierbetreuungsdienste",
   "Kunsthandwerksläden",
   "Wäschereien",
   "Tanzstudios",
   "Second-Hand-Läden",
   "Gourmet-Restaurants",
   "Schwimmbäder",
   "Veranstaltungsorte für Live-Musik",
   "Liquor Stores",
   "Gartenbauunternehmen",
   "Tauchgeschäfte",
   "Uhrengeschäfte",
   "Radsportgeschäfte",
   "Therapeuten",
   "Ski-Shops",
   "Sushi-Restaurants",
   "Fensterputzer",
   "Schlüsseldienste",
   "Cocktailbars",
   "Pizzerien",
   "Handtaschengeschäfte",
   "Ballettschulen",
   "Teppichreinigungsdienste",
   "Flughafen-Taxis",
   "Fotolabors",
   "Heimwerkerläden",

]
Gmaps.places(queries, max=150, has_website=False)

**Comment by Chetan11-dev** [comment]
Resolved run 
```
git pull
```
