### ISSUE TITLE
Not all results are coming 

### ISSUE THREAD

**Issue by ravigarg01** [omkarcloud/google-maps-scraper#76]
Hi, I think only results of first page are coming. However you mentioned that 120 results at Max should come but I'm only getting the results from 1st page.

Search query= NDA coaching in Agra

Got 16 results in json file but there were a lot more than this in next pages.

So this library doesn't offer paginated resujts?

**Comment by Chetan11-dev** [comment]
No, it scrapes all results, in your query there are few results only just visit https://www.google.com/maps/search/NDA+coaching+in+Agra/ and see it for yourself.
