### ISSUE TITLE
Chrome Version compatibility issue

### ISSUE THREAD

**Issue by ravigarg01** [omkarcloud/google-maps-scraper#77]
Recently it was working but now the script is returning chrome version compatability issues. 

    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 120
Current browser version is 119.0.6045.200 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
        GetHandleVerifier [0x00586E73+174291]
        (No symbol) [0x004B0AC1]
        (No symbol) [0x001C6FF6]
        (No symbol) [0x001EE912]
        (No symbol) [0x001EE150]
        (No symbol) [0x001EB6D4]
        (No symbol) [0x001E7A0F]
        (No symbol) [0x0021E259]
        (No symbol) [0x0021DBBA]
        (No symbol) [0x00216DA6]
        (No symbol) [0x001F1034]
        (No symbol) [0x001F1F8D]
        GetHandleVerifier [0x006249CC+820268]
        sqlite3_dbdata_init [0x006E4EBE+652494]
        sqlite3_dbdata_init [0x006E48D9+650985]
        sqlite3_dbdata_init [0x006D962C+605244]
        sqlite3_dbdata_init [0x006E586B+654971]
        (No symbol) [0x004BFEBC]
        (No symbol) [0x004B8428]
        (No symbol) [0x004B854D]
        (No symbol) [0x004A5858]
        BaseThreadInitThunk [0x76DC7BA9+25]
        RtlInitializeExceptionChain [0x776EBD2B+107]
        RtlClearBits [0x776EBCAF+191]

Retrying

DevTools listening on ws://127.0.0.1:51345/devtools/browser/de9b7c2e-24c2-45f6-8a7b-aaeb9ec71ddd

DevTools listening on ws://127.0.0.1:51356/devtools/browser/37ed28ab-c300-439d-9a61-6813e8198f14
Traceback (most recent call last):
  File "C:\Users\Developer\Envs\maps_Venv\Lib\site-packages\botasaurus\create_driver_utils.py", line 231, in create_selenium_driver
    driver = AntiDetectDriver(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\Developer\Envs\maps_Venv\Lib\site-packages\botasaurus\anti_detect_driver.py", line 31, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Developer\Envs\maps_Venv\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Developer\Envs\maps_Venv\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    super().__init__(
  File "C:\Users\Developer\Envs\maps_Venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Developer\Envs\maps_Venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Developer\Envs\maps_Venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Developer\Envs\maps_Venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 120
Current browser version is 119.0.6045.200 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
        GetHandleVerifier [0x00586E73+174291]
        (No symbol) [0x004B0AC1]
        (No symbol) [0x001C6FF6]
        (No symbol) [0x001EE912]
        (No symbol) [0x001EE150]
        (No symbol) [0x001EB6D4]
        (No symbol) [0x001E7A0F]
        (No symbol) [0x0021E259]
        (No symbol) [0x0021DBBA]
        (No symbol) [0x00216DA6]
        (No symbol) [0x001F1034]
        (No symbol) [0x001F1F8D]
        GetHandleVerifier [0x006249CC+820268]
        sqlite3_dbdata_init [0x006E4EBE+652494]
        sqlite3_dbdata_init [0x006E48D9+650985]
        sqlite3_dbdata_init [0x006D962C+605244]
        sqlite3_dbdata_init [0x006E586B+654971]
        (No symbol) [0x004BFEBC]
        (No symbol) [0x004B8428]
        (No symbol) [0x004B854D]
        (No symbol) [0x004A5858]
        BaseThreadInitThunk [0x76DC7BA9+25]
        RtlInitializeExceptionChain [0x776EBD2B+107]
        RtlClearBits [0x776EBCAF+191]

During handling of the above exception, another exception occurred:

**Comment by Chetan11-dev** [comment]
Restart your PC
