### ISSUE TITLE
Scraping gets stuck

### ISSUE THREAD

**Issue by sh3ll4rpw** [omkarcloud/google-maps-scraper#8]
OS; Debian 12
Python version 3.11.4

First I faced the error "selenium error" RecursionError: maximum recursion depth exceeded" after 10~ queries

I solved it with increasing then number in `sys.setrecursionlimit(1000)`                                                                                                                                                       

Now selenium randomly get stuck and I see no errors. This time it got stuck after 20 queries. Too bad the tool doesn't write results after each query. So far I got no results written due this problem. 

![Screenshot from 2023-06-30 23-47-05](https://github.com/omkarcloud/google-maps-scraper/assets/113100850/e620ede9-90b0-429d-b510-b9e5de1f95dc)

Its stuck for 2 hours and when I run the scraper again it works until it get stuck again. I enabled selenium logging but I can't find my errors. Any idea what it can be so I can look into it?

**Comment by Chetan11-dev** [comment]
Should be fixes in v2

**Comment by sh3ll4rpw** [comment]
Perfect. Socks5 support in V2 too?

**Comment by Chetan11-dev** [comment]
I don't know how to do it? Could you patch v2 (Once Released) and send me the Code I will learn it.

**Comment by sh3ll4rpw** [comment]
I just see it can be easily done with an argument. `https://stackoverflow.com/questions/53082267/how-can-i-set-socks5-proxy-for-selenium-webdriver-python`  Not necessary to add this to your code.

**Comment by Chetan11-dev** [comment]
Yes, I am not adding it.

**Comment by sh3ll4rpw** [comment]
Can you re-open this issue? It's not resolved in V2. Scraper got stuck fetching links **exactly** at the same place as on the screenshot

**Comment by sh3ll4rpw** [comment]
queries:
```

**Comment by sh3ll4rpw** [comment]
I took another selection of queries. It keep getting stuck after fetching the 9th query. I run it 4 time in a row to check what happens. Now it gets stuck after fetching the second query every time I run the scraper

**Comment by Chetan11-dev** [comment]
It has to be a selenium issue. My advice you is to get a friend's computer and run it there, till some one comes and provide solution. As I really don't know why it occurs.

**Comment by Chetan11-dev** [comment]
@sh3ll4rpw, It was a coding bug, I resolved it please use latest version.
