### ISSUE TITLE
Hello! I have a list of locations with their respective geo-coordinates. Currently, I am running the following code:

### ISSUE THREAD

**Issue by FayzulSaimun** [omkarcloud/google-maps-scraper#82]
Hello! I have a list of locations with their respective geo-coordinates. Currently, I am running the following code:

```
for city in tqdm(batch):
        query = f"{city['city']}, {city['state_name']} karaoke"
        queries = [query]
        coordinate_string = f"{city['lat']},{city['lng']}"
        data = Gmaps.places(
            queries, fields=Gmaps.ALL_FIELDS, geo_coordinates=coordinate_string, zoom=16
        )
```
I tried this way also but it didn't work
```
queries = [{'keywords': 'erie pennsylvania karaoke', 'geo_coordinates': '42.10958,-80.104055', 'zoom': 16}]
Gmaps.places(queries, fields=Gmaps.ALL_FIELDS)
```

Can the full list be given to the scraper without the loop to minimize the run time? Currently, it takes a lot of time to get 100 location results.

_Originally posted by @FayzulSaimun in https://github.com/omkarcloud/google-maps-scraper/discussions/81_

**Comment by Chetan11-dev** [comment]
Answered in Discussion
