### ISSUE TITLE
EGL Driver Message Error!!

### ISSUE THREAD

**Issue by alexandrexgoulart** [omkarcloud/google-maps-scraper#85]
Can anyone help with this issue ?

![PC error](https://github.com/omkarcloud/google-maps-scraper/assets/78564138/9e1bfc06-40a6-446e-aeec-737dcac1cda0)

**Comment by FayzulSaimun** [comment]
You can ignore these errors.

**Comment by alexandrexgoulart** [comment]
> You can ignore these errors.

How do I ignore these errors and still run the application ?

**Comment by Chetan11-dev** [comment]
Just don't do anything simply ignore. These are Google Chrome Error's. Everything is fine.
