### ISSUE TITLE
Only small number of results (36) are returned.

### ISSUE THREAD

**Issue by r28289** [omkarcloud/google-maps-scraper#91]
### Description

I have removed the max=5 parameter and expect to get many results, probably 120 now. Something prevents this and I am getting the following messages:
"Google Maps was stuck in scrolling. Retrying"
after 5 unsuccessfull attempts it skipps and aborts.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by Chetan11-dev** [comment]
You might have been silently blocked by Google, kindly follow these Steps if it happens again:
1.  Connect your PC to the Internet via a Mobile Hotspot.
2.  Toggle airplane mode off and on on your mobile device. This will assign you a new IP address.
3.  Turn the hotspot back on.
