### ISSUE TITLE
Google Maps was stuck in scrolling. Retrying.

### ISSUE THREAD

**Issue by paulanka2000** [omkarcloud/google-maps-scraper#96]
### Description

I get some scraping results but most of the time the program is getting Google Maps was stuck in scrolling. Retrying.

the older version didn't give me nearly as many problems

### Code to Reproduce (Paste `main.py`)
queries = Gmaps.Cities.UnitedStates("plumber in")

fields = [
   Gmaps.Fields.NAME,
   Gmaps.Fields.PHONE,
]
Gmaps.places(queries, fields=fields)

results:

(PycharmProjects) PS C:\Users\Paul\PycharmProjects\google-maps-scraper-pro-master> python main.py
Running

DevTools listening on ws://127.0.0.1:26463/devtools/browser/2e86adac-30e2-4e80-87eb-abddcbce9a89
Google Maps was stuck in scrolling. Retrying.
Retrying
Google Maps was stuck in scrolling. Retrying.
Retrying
Google Maps was stuck in scrolling. Retrying.
Retrying

### Zip and Upload the `error_log/` Folder (Optional, if there are errors)

**Comment by Chetan11-dev** [comment]
released fix
