### ISSUE TITLE
New release causes an error in Scraper.py

### ISSUE THREAD

**Issue by Cacti4** [omkarcloud/google-maps-scraper#98]
### Description

Didn't have this problem in the old version.

### Code to Reproduce (Paste `main.py`)

```python
from src import Gmaps

love_it_star_it = '''Love It? Star It! ⭐ https://github.com/omkarcloud/google-maps-scraper/'''

queries = ["restaurant in California"]
Gmaps.places(queries, min_reviews=10, has_phone=True, has_website=False) 
```

Error:

TypeError: request() got an unexpected keyword argument 'use_stealth'

**Comment by Chetan11-dev** [comment]
Please follow these Steps. 

⿡ Clone the Magic 🧙‍♀:
```
git clone https://github.com/omkarcloud/outlook-account-generator
cd outlook-account-generator
```

⿢ Install Dependencies 📦:
```
python -m pip install -r requirements.txt
```

⿣ Let's Roll 😎:
```
python main.py 
```

And Run the following command to update packages:

```
python -m pip install botasaurus --upgrade
```

**Comment by Cacti4** [comment]
First of all, that is for the wrong repository, second of all, I stated that it was working before the update, and a change made it not work. Sorry if I was not clear about my problem.
